### ISSUE TITLE
problem with composer

### ISSUE THREAD

**Issue by strauss69400** [whatwedo/PostFinanceEPayment#4]
hi,

i'm interesting by your extension!!i tried to install via composer like this : 
"composer require whatwedo/postfinance-e-payment".

unfortunately, i got this error : 
 [InvalidArgumentException]
  Could not find package whatwedo/postfinance-e-payment at any version for your minimum-stability (stable).  Check the package spelling or your minimum-stability.

Do you have a solution to bypass this problem?
thank you very much for your help and well done for your extension

**Comment by xarem** [comment]
Hey @strauss69400 

Because we couldn't test it in multiple projects we didn't release any stable version of the library yet.

you can install the master branch (current production version) using the following command:

```
composer require whatwedo/postfinance-e-payment dev-master
```

**Comment by strauss69400** [comment]
ok thank you very much
