### ISSUE TITLE
Status Change 5 to 9

### ISSUE THREAD

**Issue by strauss69400** [whatwedo/PostFinanceEPayment#5]
HI,

I come to you on a question about the status.
First, the code you provides in the doc works perfectly !! Great job.

currently when an order is placed the status is 5.
and I would like from my site,to apply for the status to become 9

How can I do this with your module.?
it is possible?

thanks for your help

**Comment by xarem** [comment]
Hey @strauss69400

Are you making an authorization request only (to charge the account f.ex. in a week)? If yes, you have to implement a backend logic for this - this library does not support any PostFinance API calls yet. Feel free to fork and make a push request - i would be happy :)

If your payment request is charging the money directly (f.ex. in most online shops), the status will be automatically changed as soon as PostFinance is charging the money from the card holder to pay you.

Kind regards
Ueli

**Comment by strauss69400** [comment]
sorry, i forget to response to your proposition.
Indeed, in the administration of postfinance, there is an option that call one per day the data-capture.
this data-capture allows to change the status from 5 to 9.
to improve your library, i don't know if i am able to add this functionality!!sorry
